name: deploy to lambda
on: [push]
env:
  AWS_REGION: eu-north-1

jobs:
  deploy:
    name: build and deploy lambda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
            java-version: '17'
            distribution: 'corretto'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
        env:
          EMAIL_ADDRESS_FROM: ${{vars.EMAIL_ADDRESS_FROM}}
          EMAIL_ADDRESS_TO: ${{vars.EMAIL_ADDRESS_TO}}
      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws_region: eu-north-1
          function_name: fuelprices
          zip_file: build/libs/aws-0.0.1-SNAPSHOT-all.jar